# Generated by Django 4.2.25 on 2026-09-21 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Tiêu đề')),
                ('publication_date', models.DateField(verbose_name='Ngày xuất bản')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('cover', models.ImageField(blank=True, upload_to='book_covers/', verbose_name='Ảnh bìa')),
                ('sample', models.FileField(blank=True, upload_to='book_samples/', verbose_name='Bản mẫu')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=50, verbose_name='Tên')),
                ('last_names', models.CharField(max_length=50, verbose_name='Họ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cộng tác viên',
                'verbose_name_plural': 'Cộng tác viên',
                'ordering': ['last_names', 'first_names'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên nhà xuất bản')),
                ('website', models.URLField(verbose_name='Website')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Nhà xuất bản',
                'verbose_name_plural': 'Nhà xuất bản',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung đánh giá', verbose_name='Nội dung')),
                ('rating', models.IntegerField(help_text='Điểm từ 0 đến 5', verbose_name='Điểm')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('date_edited', models.DateTimeField(blank=True, null=True, verbose_name='Ngày sửa')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.book', verbose_name='Sách')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người viết')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BookContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('AUTHOR', 'Tác giả'), ('CO_AUTHOR', 'Đồng tác giả'), ('EDITOR', 'Biên tập')], max_length=20, verbose_name='Vai trò')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.book')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.contributor')),
            ],
            options={
                'verbose_name': 'Vai trò cộng tác',
                'verbose_name_plural': 'Vai trò cộng tác',
                'unique_together': {('book', 'contributor', 'role')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='contributors',
            field=models.ManyToManyField(through='reviews.BookContributor', to='reviews.contributor', verbose_name='Cộng tác viên'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.publisher', verbose_name='Nhà xuất bản'),
        ),
    ]
