# Generated by Django 4.2.25 on 2026-09-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung chi tiết'),
        ),
        migrations.AddField(
            model_name='book',
            name='sample_video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Đường dẫn/Tên file Video'),
        ),
    ]
